const ProtienShakesData = [
    {
        id: 1,
        ProtienShakeImage: "https://img4.hkrtcdn.com/30466/prd_3046513-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Rich-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey",
        ProtienShakeDesc: "2 kg, Rich Chocolate",
        ProtienShakePrice: 3899,
    },
    {
        id: 2,
        ProtienShakeImage: "https://img8.hkrtcdn.com/30466/prd_3046527-MuscleBlaze-Biozyme-Performance-Whey-8.8-lb-Rich-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey",
        ProtienShakeDesc: "4 kg, Rich Chocolate",
        ProtienShakePrice: 7399,
    },
    {
        id: 3,
        ProtienShakeImage: "https://img3.hkrtcdn.com/27525/prd_2752462-MuscleBlaze-80-Raw-Whey-Protein-Supplement-Powder-2.2-lb-33-Servings-Unflavoured_c_s.jpg",
        ProtienShakeTitle: "80% Raw Whey Protein Supplement Powder",
        ProtienShakeDesc: "1 kg, Unflavoured",
        ProtienShakePrice: 1649,
    },
    {
        id: 4,
        ProtienShakeImage: "https://img2.hkrtcdn.com/30466/prd_3046521-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Chocolate-Hazelnut_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey",
        ProtienShakeDesc: "2 kg, Chocolate Hazelnut",
        ProtienShakePrice: 3899,
    },
    {
        id: 5,
        ProtienShakeImage: "https://img3.hkrtcdn.com/27461/prd_2746072-MB-Fuel-One-Whey-Protein-Immunity-4.4-lb-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Fuel One Whey Protein",
        ProtienShakeDesc: "2 kg, Chocolate",
        ProtienShakePrice: 3399,
    },
    {
        id: 11,
        ProtienShakeImage: "https://img8.hkrtcdn.com/28714/prd_2871317-MB-Fuel-One-Whey-Protein-2.2-lb-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Fuel One Whey Protein",
        ProtienShakeDesc: "1 kg, Chocolate",
        ProtienShakePrice: 1749,
    },
    {
        id: 12,
        ProtienShakeImage: "https://img4.hkrtcdn.com/30466/prd_3046543-MuscleBlaze-Biozyme-Performance-Whey-PR-4.4-lb-Chocolate-Fudge_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey PR",
        ProtienShakeDesc: "2 kg, Chocolate Fudge",
        ProtienShakePrice: 4199,
    },
    {
        id: 13,
        ProtienShakeImage: "https://img4.hkrtcdn.com/29745/prd_2974433-MuscleBlaze-Whey-Gold-Protein-Isolate-with-Digezyme-8.8-lb-Rich-Milk-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Whey Gold Protein Isolate with Digezyme",
        ProtienShakeDesc: "4 kg, Rich Milk Chocolate",
        ProtienShakePrice: 10800,
    },
    {
        id: 14,
        ProtienShakeImage: "https://img5.hkrtcdn.com/22104/prd_2210394-MB-Fuel-One-Black-Whey-Protein-1.65-lb-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Fuel One Black Whey Protein",
        ProtienShakeDesc: "750 g, Chocolate",
        ProtienShakePrice: 1999,
    },
    {
        id: 15,
        ProtienShakeImage: "https://img1.hkrtcdn.com/27426/prd_2742560-MuscleBlaze-Biozyme-Performance-Whey-0.079-lb-Rich-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey",
        ProtienShakeDesc: "36 g, Rich Chocolate",
        ProtienShakePrice: 139,
    },
    {
        id: 6,
        ProtienShakeImage: "https://img4.hkrtcdn.com/30466/prd_3046543-MuscleBlaze-Biozyme-Performance-Whey-PR-4.4-lb-Chocolate-Fudge_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey PR",
        ProtienShakeDesc: "2 kg, Chocolate Fudge",
        ProtienShakePrice: 4199,
    },
    {
        id: 7,
        ProtienShakeImage: "https://img3.hkrtcdn.com/27462/prd_2746112-MuscleBlaze-Whey-Gold-100-Whey-Protein-Isolate-4.4-lb-Rich-Milk-Chocolate_c_s.jpg",
        ProtienShakeTitle: "Whey Gold 100% Whey Protein Isolate",
        ProtienShakeDesc: "2 kg, Rich Milk Chocolate",
        ProtienShakePrice: 6399,
    },
    {
        id: 8,
        ProtienShakeImage: "https://img4.hkrtcdn.com/30466/prd_3046533-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Blue-Tokai-Coffee_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey",
        ProtienShakeDesc: "2 kg, Blue Tokai Coffee",
        ProtienShakePrice: 3899,
    },
    {
        id: 9,
        ProtienShakeImage: "https://img8.hkrtcdn.com/30466/prd_3046517-MuscleBlaze-Biozyme-Performance-Whey-4.4-lb-Magical-Mango_c_s.jpg",
        ProtienShakeTitle: "Biozyme Performance Whey PR",
        ProtienShakeDesc: "2 kg, Magical Mango",
        ProtienShakePrice: 4199,
    },
    {
        id: 10,
        ProtienShakeImage: "https://img9.hkrtcdn.com/27298/prd_2729758-MuscleBlaze-100-Whey-Protein-Supplement-Powder-with-Digestive-Enzyme-4-lb-54-Servings-Rich-Milk-Chocolate_c_s.jpg",
        ProtienShakeTitle: "100% Whey Protein Powder with Digestive Enzyme",
        ProtienShakeDesc: "2 kg, Rich Milk Chocolate",
        ProtienShakePrice: 4799,
    },
    

]

export default ProtienShakesData;